const Sequelize = require('sequelize');
const configDB = require('../config/database');

const User = require('../models/user')
const Unidade = require('../models/unidade')
const Agenda = require('../models/agenda')
const Cidade = require('../models/cidade')
const Clinica = require('../models/clinica')
const Contas_pagar = require('../models/contas_pagar')
const Contas_receber = require('../models/contas_receber')
const Convenios = require('../models/convenios')
const Despesas = require('../models/despesas')
const Doencas = require('../models/doencas')
const Especialidades = require('../models/especialidades')
const Estados = require('../models/estados')
const Estoques = require('../models/estoques')
const FormasPagamento = require('../models/formaspagamento')
const Fornecedores = require('../models/fornecedores')
const ImagensTratamento = require('../models/imagens_tratamento') 
const ItensDespesas = require('../models/itens_despesas')
const ItensOrcamento = require('../models/itens_orcamento')
const Medicamentos = require('../models/medicamentos')
const Orcamentos = require('../models/orcamentos')
const Pacientes = require('../models/pacientes')
const Perfis = require('../models/perfis')
const Plano_Pagamento = require('../models/plano_pagamento')
const Planos_Conta = require('../models/planos_conta')
const Procedimentos = require('../models/procedimentos')
const Prontuario = require('../models/prontuario')
const Prontuario_Tratamento = require('../models/prontuario_tratamento')
const Proteses = require('../models/proteses')
const Questoes_Anamnese = require('../models/questoes_anamnese')
const Recibos = require('../models/recibos')
// const Retornos = require('../models/retornos')
// const Retornos_Paciente = require('../models/retornos_Paciente')
const Segmentos = require('../models/segmentos')
const Situacoes_Agenda = require('../models/situacoes_agenda')
const Tipo_Agendamento = require('../models/tipo_agendamento')
const Tratamentos = require('../models/tratamentos')

const connection = new Sequelize(configDB)

User.init(connection)
Unidade.init(connection)
Agenda.init(connection)
Cidade.init(connection)
Clinica.init(connection)
Contas_pagar.init(connection)
Contas_receber.init(connection)
Convenios.init(connection)
Despesas.init(connection)
Doencas.init(connection)
Especialidades.init(connection)
Estados.init(connection)
Estoques.init(connection)
FormasPagamento.init(connection)
Fornecedores.init(connection)
ImagensTratamento.init(connection)
ItensDespesas.init(connection)
ItensOrcamento.init(connection)
Medicamentos.init(connection)
Orcamentos.init(connection)
Pacientes.init(connection)
Perfis.init(connection)
Plano_Pagamento.init(connection)
Planos_Conta.init(connection)
Procedimentos.init(connection)
Prontuario.init(connection)
Prontuario_Tratamento.init(connection)
Proteses.init(connection)
Questoes_Anamnese.init(connection)
Recibos.init(connection)
// Retornos.init(connection)
// Retornos_Paciente.init(connection)
Segmentos.init(connection)
Situacoes_Agenda.init(connection)
Tipo_Agendamento.init(connection)
Tratamentos.init(connection)

module.exports = connection

